// src/config/theme.ts
// Canonical executable theme layer for Marriage OS V1.
// This file governs visual tokens, naming overlays, copy rules, and component constraints.

import type { NavItem } from './routes';

export type ThemeState =
  | 'stable'
  | 'drift'
  | 'resentment-building'
  | 'entrenched-resentment';

export type FontRole =
  | 'marketingHero'
  | 'appTitle'
  | 'body'
  | 'label'
  | 'button'
  | 'nav'
  | 'meta';

export type RepairCategorySlug =
  | 'stop-damage'
  | 'restore-bond'
  | 'repair-desire'
  | 'overload-life-phase'
  | 'threats-to-system'
  | 'stay-and-rebuild';

export const theme = {
  meta: {
    name: 'marriage-os-canonical-v1',
    mode: 'calm-premium',
    canonical: true,
    notes: [
      'Website with app shell',
      'Repair remains the centre of V1',
      'One dominant CTA per screenful',
      'Marketing uses serif selectively; app stays sans-first',
      'Marketing uses the warm accent layer as invitation; member/app remains blue-led and tool-first',
      'Repair is the intervention surface; Guides/Perspectives are the meaning layer; Knowledge is the reference layer',
      'Knowledge detail pages use ArticleSection, not card-only rendering',
      'BP-302 visual fluency rule: one dominant next action, one support layer, secondary choices recede',
    ],
  },

  fonts: {
    variables: {
      sans: '--font-ui-sans',
      serif: '--font-display-serif',
      mono: '--font-mono',
    },
    stacks: {
      sans: `var(--font-ui-sans), Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Arial, sans-serif`,
      serif: `var(--font-display-serif), Fraunces, "Iowan Old Style", "Palatino Linotype", "Book Antiqua", Georgia, "Noto Serif", serif`,
      mono: `var(--font-mono), "JetBrains Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace`,
    },
    roleRules: {
      marketingHero: {
        font: 'serif',
        allowedOn: ['homepage hero', 'pricing hero', 'store hero', 'how-it-works hero'],
        bannedOn: ['today', 'repair', 'check-in', 'forms', 'buttons', 'state cards', 'progress'],
        maxLines: 2,
      },
      appTitle: {
        font: 'sans',
        allowedOn: ['member pages', 'repair modules', 'state pages', 'guides', 'knowledge'],
        bannedOn: [],
        maxLines: 2,
      },
      body: {
        font: 'sans',
        allowedOn: ['all body copy', 'knowledge articles', 'guides', 'pricing', 'product detail'],
        bannedOn: [],
      },
      label: {
        font: 'sans',
        allowedOn: ['chips', 'badges', 'labels'],
        bannedOn: [],
      },
      button: {
        font: 'sans',
        allowedOn: ['all controls'],
        bannedOn: ['none'],
      },
      nav: {
        font: 'sans',
        allowedOn: ['top bar', 'bottom nav', 'side nav', 'breadcrumbs'],
        bannedOn: [],
      },
      meta: {
        font: 'mono',
        allowedOn: ['timestamps', 'debug panels', 'payload disclosures'],
        bannedOn: ['hero', 'body', 'button'],
      },
    } satisfies Record<FontRole, Record<string, unknown>>,
  },

  color: {
    base: {
      obsidianNavy: '#0F1724',
      deepSlate: '#1A2433',
      softInk: '#243247',
      warmIvory: '#F7F4EE',
      stoneMist: '#E7E1D6',
      lineSoft: 'rgba(255,255,255,0.08)',
      lineLight: 'rgba(15,23,36,0.10)',
    },
    brand: {
      cognitiveBlue: '#4E7BFF',
      mutedBlue: '#8EABFF',
      paleBlueGlow: '#DCE7FF',
    },
    warmAccent: {
      ember: '#D04F1C',
      deepEmber: '#7B1D0A',
      emberGlow: 'rgba(244,120,42,0.16)',
      amberText: 'rgba(248,194,138,0.86)',
      amberTextSoft: 'rgba(248,194,138,0.84)',
      amberLine: 'rgba(255,172,117,0.35)',
      amberLineSoft: 'rgba(246,175,108,0.16)',
      emberCardLine: 'rgba(255,180,128,0.20)',
      emberBadgeBg: 'rgba(248,120,49,0.14)',
      emberBadgeLine: 'rgba(255,179,128,0.18)',
      emberIcon: 'rgba(255,191,112,0.94)',
      warmText: '#FBF4EA',
      warmTextStrong: '#FFF7EF',
      warmTextMuted: 'rgba(248,239,227,0.84)',
      warmTextSoft: 'rgba(250,239,224,0.94)',
      warmButtonText: '#FFF8F2',
    },
    state: {
      stable: '#6E9B7D',
      drift: '#C89A3D',
      resentmentBuilding: '#B8772F',
      entrenchedResentment: '#9B5C52',
    },
    text: {
      onDark: '#F7F4EE',
      onDarkMuted: 'rgba(247,244,238,0.76)',
      onLight: '#132032',
      onLightMuted: 'rgba(19,32,50,0.72)',
      inverse: '#FFFFFF',
    },
    surface: {
      appShell: '#0F1724',
      appElevated: '#1A2433',
      appSelected: '#243247',
      marketingShell: '#F7F4EE',
      cardLight: '#FFFFFF',
      cardDark: '#1A2433',
      cardMuted: 'rgba(255,255,255,0.04)',
    },
    badge: {
      stableBg: 'rgba(110,155,125,0.16)',
      driftBg: 'rgba(200,154,61,0.16)',
      resentmentBuildingBg: 'rgba(184,119,47,0.16)',
      entrenchedResentmentBg: 'rgba(155,92,82,0.16)',
    },
  },

  typography: {
    hero: {
      fontFamily: 'serif',
      mobileSize: 'clamp(1.875rem, 1.2rem + 2.2vw, 2.75rem)',
      desktopSize: 'clamp(2.25rem, 1.7rem + 1.8vw, 3.5rem)',
      lineHeight: 1.05,
      letterSpacing: '-0.025em',
      maxLines: 2,
    },
    appTitle: {
      fontFamily: 'sans',
      size: 'clamp(1.75rem, 1.3rem + 1.6vw, 2.5rem)',
      lineHeight: 1.15,
      letterSpacing: '-0.02em',
      maxLines: 2,
    },
    body: {
      fontFamily: 'sans',
      size: 'clamp(1.0625rem, 0.9rem + 0.4vw, 1.1875rem)',
      lineHeight: 1.55,
      letterSpacing: '-0.01em',
    },
    bodyLoose: {
      fontFamily: 'sans',
      size: 'clamp(1.0625rem, 0.9rem + 0.4vw, 1.1875rem)',
      lineHeight: 1.62,
      letterSpacing: '-0.01em',
    },
    subhead: {
      fontFamily: 'sans',
      size: 'clamp(1.25rem, 1.05rem + 0.8vw, 1.5rem)',
      lineHeight: 1.2,
      letterSpacing: '-0.015em',
    },
    label: {
      fontFamily: 'sans',
      size: '0.875rem',
      lineHeight: 1.2,
      weight: 600,
    },
    button: {
      fontFamily: 'sans',
      size: '0.95rem',
      lineHeight: 1,
      weight: 600,
      letterSpacing: '-0.01em',
    },
    meta: {
      fontFamily: 'mono',
      size: '0.8125rem',
      lineHeight: 1.3,
    },
    measure: {
      readingTarget: '66ch',
      readingMax: '75ch',
    },
  },

  layout: {
    minViewportHeight: '100dvh',
    headerHeightMobile: '4rem',
    headerHeightDesktop: '4.5rem',
    bottomNavHeight: '4.75rem',
    contentMaxWidth: '80rem',
    readingTargetWidth: '66ch',
    readingMaxWidth: '75ch',
    shellPaddingInlineMobile: '1rem',
    shellPaddingInlineDesktop: '1.5rem',
    safeAreaTop: 'max(1rem, env(safe-area-inset-top))',
    safeAreaRight: 'max(1rem, env(safe-area-inset-right))',
    safeAreaBottom: 'max(1rem, env(safe-area-inset-bottom))',
    safeAreaLeft: 'max(1rem, env(safe-area-inset-left))',
  },

  interaction: {
    targetMin: 44,
    targetComfort: 48,
    targetGap: 8,
    transitionFast: '140ms ease',
    transitionStandard: '220ms ease',
  },

  visualHierarchy: {
    screenRule: 'one-primary-decision',
    primaryAction: {
      role: 'dominant next action',
      background: 'linear-gradient(180deg, rgba(31, 54, 90, 0.98), rgba(22, 37, 61, 0.98))',
      backgroundHover: 'linear-gradient(180deg, rgba(39, 66, 107, 0.98), rgba(25, 43, 70, 0.98))',
      border: 'rgba(159, 201, 255, 0.46)',
      shadow: '0 18px 34px rgba(3, 8, 18, 0.2)',
      text: '#F4F7FF',
    },
    supportPanel: {
      role: 'secondary explanation layer',
      background: 'rgba(12, 20, 32, 0.5)',
      border: 'rgba(166, 191, 226, 0.1)',
      text: 'rgba(232, 240, 255, 0.82)',
    },
    quietPanel: {
      role: 'tertiary / receding layer',
      background: 'rgba(8, 14, 24, 0.34)',
      border: 'rgba(166, 191, 226, 0.08)',
      text: 'rgba(212, 226, 248, 0.72)',
    },
    disclosure: {
      role: 'optional exploration',
      background: 'rgba(9, 15, 25, 0.32)',
      border: 'rgba(166, 191, 226, 0.09)',
    },
    appAccent: {
      role: 'controlled member-shell contrast, not primary app action colour',
      heading: 'rgba(248, 194, 138, 0.92)',
      headingSoft: 'rgba(248, 194, 138, 0.72)',
      icon: 'rgba(255, 191, 112, 0.92)',
      rule: 'rgba(248, 194, 138, 0.18)',
      chipBackground: 'rgba(248, 120, 49, 0.1)',
      chipBorder: 'rgba(255, 179, 128, 0.22)',
    },
    scanStructure: {
      stepIndexBackground: 'rgba(248, 120, 49, 0.13)',
      stepIndexBorder: 'rgba(255, 179, 128, 0.28)',
      stepRowBackground: 'rgba(8, 14, 24, 0.44)',
      stepRowBorder: 'rgba(166, 191, 226, 0.1)',
      optionRowBackground: 'rgba(8, 14, 24, 0.38)',
      optionRowBorder: 'rgba(166, 191, 226, 0.09)',
    },
    bottomNav: {
      background: 'rgba(15, 24, 38, 0.78)',
      activeBackground: 'rgba(31, 49, 76, 0.62)',
      activeBorder: 'rgba(159, 201, 255, 0.18)',
      shadow: '0 14px 28px rgba(4, 10, 19, 0.24)',
    },
    mobileViewport: {
      role: 'member-shell containment and narrow-screen rhythm',
      appInlinePadding: 'clamp(0.5rem, 3vw, 0.9rem)',
      appHeaderPadding: '0.58rem 0.68rem',
      appHeaderGap: '0.55rem',
      appIconButtonSize: '2.35rem',
      appPanelPadding: 'clamp(0.82rem, 4vw, 1.05rem)',
      appPanelRadius: '1rem',
      appNarrowPanelRadius: '0.9rem',
      bottomNavItemBasis: '4.05rem',
    },
    marketing: {
      accentCardBackground: 'linear-gradient(180deg, rgba(166, 55, 18, 0.88), rgba(115, 32, 13, 0.9))',
      quietCardBackground: 'rgba(18, 28, 43, 0.58)',
      warmAccentLimit: 'use one dominant warm card group per screenful; supporting cards recede',
    },
  },

  copyRules: {
    heroMaxLines: 2,
    subtitleMaxSentences: 2,
    primaryCtasAboveFold: 1,
    secondaryCtasAboveFoldMax: 1,
    avoidGenericContinue: true,
    headlineToCtaMessageMatch: true,
    scanPagesUseCardsNotEssays: true,
  },

  labels: {
    nav: {
      today: 'Today',
      repair: 'Repair',
      guides: 'Perspectives',
      knowledge: 'Knowledge',
      progress: 'Progress',
    } satisfies Record<NavItem, string>,
    repairCategories: {
      'stop-damage': 'Stop Damage',
      'restore-bond': 'Restore Bond',
      'repair-desire': 'Attraction & Desire',
      'overload-life-phase': 'Life Pressure',
      'threats-to-system': 'External Pressure',
      'stay-and-rebuild': 'Stay & Rebuild',
    } satisfies Record<RepairCategorySlug, string>,
    stateHelpers: {
      stable: 'Things are broadly steady.',
      drift: 'Some distance is forming.',
      'resentment-building': 'Strain is becoming a pattern.',
      'entrenched-resentment': 'Distance is now deeply set.',
    } satisfies Record<ThemeState, string>,
  },

  componentRules: {
    appShell: {
      surface: 'dark',
      safeAreaAware: true,
      minHeight: '100dvh',
      fixedWhitePanelsForbidden: true,
    },
    marketingShell: {
      surface: 'light',
      stickyHeader: true,
    },
    topBar: {
      sticky: true,
      maxRightActions: 2,
    },
    bottomNav: {
      itemCount: 5,
      labelsAlwaysVisible: true,
      minTargetPx: 48,
      mustNotCompeteWithPrimaryAction: true,
    },
    heroBlock: {
      titleMaxLines: 2,
      subtitleMaxSentences: 2,
      primaryCtaRequired: true,
      allowIllustrationOnMemberPages: false,
    },
    card: {
      fixedHeightCopyForbidden: true,
      nestedCardsDiscouraged: true,
      radius: '1.25rem',
      defaultPadding: '1.25rem',
    },
    stateBadge: {
      colorOnlyForbidden: true,
      helperLineRequired: true,
    },
    nextBestMoveCard: {
      oneActionOnly: true,
      mustBeVisuallyDominant: true,
      timeEstimateRequired: true,
      toneGuidanceRequired: true,
      successConditionRequired: true,
    },
    makeItWorseCard: {
      defaultCollapsed: true,
      maxVisibleItemsBeforeExpand: 5,
      bulletsMustBeVerbLed: true,
    },
    quickScriptCard: {
      copyButtonRequired: true,
      whenToUseRequired: true,
      whenNotToUseRequired: true,
    },
    repairModuleHero: {
      bestUsedWhenRequired: true,
      notForRequired: true,
      resetLengthRequired: true,
    },
    productCard: {
      problemSolvedRequired: true,
      bulletsMax: 3,
      priceQuiet: true,
    },
  },
} as const;

export const cssVariables = {
  '--font-ui-sans': '"Inter Variable"',
  '--font-display-serif': '"Fraunces Variable"',
  '--font-mono': '"JetBrains Mono Variable"',
  '--color-obsidian-navy': theme.color.base.obsidianNavy,
  '--color-deep-slate': theme.color.base.deepSlate,
  '--color-soft-ink': theme.color.base.softInk,
  '--color-warm-ivory': theme.color.base.warmIvory,
  '--color-stone-mist': theme.color.base.stoneMist,
  '--color-line-light': theme.color.base.lineLight,
  '--color-text-on-light': theme.color.text.onLight,
  '--color-text-on-dark': theme.color.text.onDark,
  '--color-cognitive-blue': theme.color.brand.cognitiveBlue,
  '--color-muted-blue': theme.color.brand.mutedBlue,
  '--color-pale-blue-glow': theme.color.brand.paleBlueGlow,
  '--color-ember': theme.color.warmAccent.ember,
  '--color-deep-ember': theme.color.warmAccent.deepEmber,
  '--color-ember-glow': theme.color.warmAccent.emberGlow,
  '--color-amber-text': theme.color.warmAccent.amberText,
  '--color-amber-text-soft': theme.color.warmAccent.amberTextSoft,
  '--color-amber-line': theme.color.warmAccent.amberLine,
  '--color-amber-line-soft': theme.color.warmAccent.amberLineSoft,
  '--color-ember-card-line': theme.color.warmAccent.emberCardLine,
  '--color-ember-badge-bg': theme.color.warmAccent.emberBadgeBg,
  '--color-ember-badge-line': theme.color.warmAccent.emberBadgeLine,
  '--color-ember-icon': theme.color.warmAccent.emberIcon,
  '--color-warm-panel-text': theme.color.warmAccent.warmText,
  '--color-warm-card-title': theme.color.warmAccent.warmTextStrong,
  '--color-warm-card-body': theme.color.warmAccent.warmTextMuted,
  '--color-warm-button-text': theme.color.warmAccent.warmButtonText,
  '--color-warm-button-secondary-text': theme.color.warmAccent.warmTextSoft,
  '--color-app-shell': theme.color.surface.appShell,
  '--color-app-elevated': theme.color.surface.appElevated,
  '--color-marketing-shell': theme.color.surface.marketingShell,
  '--color-primary': theme.color.brand.cognitiveBlue,
  '--color-primary-soft': theme.color.brand.paleBlueGlow,
  '--text-on-dark': theme.color.text.onDark,
  '--text-on-light': theme.color.text.onLight,
  '--safe-top': theme.layout.safeAreaTop.replace('1rem', '0.75rem'),
  '--safe-right': theme.layout.safeAreaRight.replace('1rem', '0.75rem'),
  '--safe-bottom': theme.layout.safeAreaBottom.replace('1rem', '0.75rem'),
  '--safe-left': theme.layout.safeAreaLeft.replace('1rem', '0.75rem'),
  '--shell-rhythm-gap': 'clamp(0.7rem, 2vw, 1rem)',
  '--shell-topbar-height': '3.15rem',
  '--shell-bottom-nav-height': '3.7rem',
  '--shell-content-width': 'min(58rem, 100%)',
  '--card-border': 'rgba(132, 152, 185, 0.2)',
  '--card-shadow': '0 20px 40px rgba(3, 8, 18, 0.22)',
  '--app-surface': 'rgba(14, 23, 36, 0.86)',
  '--app-surface-soft': 'rgba(15, 24, 38, 0.64)',
  '--app-surface-muted': 'rgba(11, 18, 29, 0.46)',
  '--app-surface-strong': 'rgba(22, 36, 58, 0.92)',
  '--app-border': 'rgba(166, 191, 226, 0.16)',
  '--app-border-muted': 'rgba(166, 191, 226, 0.12)',
  '--app-border-strong': 'rgba(134, 177, 240, 0.34)',
  '--app-focus': 'rgba(159, 201, 255, 0.88)',
  '--app-focus-strong': 'rgba(159, 201, 255, 0.95)',
  '--app-focus-soft': 'rgba(159, 201, 255, 0.52)',
  '--app-focus-muted': 'rgba(159, 201, 255, 0.78)',
  '--app-link': 'rgba(226, 238, 255, 0.94)',
  '--app-text-strong': '#f4f7ff',
  '--app-text': 'rgba(247, 244, 238, 0.9)',
  '--app-text-warm': 'rgba(247, 244, 238, 0.88)',
  '--app-text-soft': 'rgba(232, 240, 255, 0.9)',
  '--app-text-muted': 'rgba(247, 244, 238, 0.7)',
  '--app-helper': 'rgba(199, 216, 244, 0.78)',
  '--app-helper-contrast': 'rgba(232, 240, 255, 0.88)',
  '--app-border-subtle': 'rgba(255, 255, 255, 0.08)',
  '--app-border-soft': 'rgba(255, 255, 255, 0.12)',
  '--app-border-mid': 'rgba(255, 255, 255, 0.14)',
  '--app-border-hover': 'rgba(255, 255, 255, 0.18)',
  '--app-white-wash': 'rgba(255, 255, 255, 0.04)',
  '--app-white-hairline': 'rgba(255, 255, 255, 0.02)',
  '--app-shadow': '0 22px 48px rgba(2, 8, 18, 0.28)',
  '--app-shadow-soft': '0 18px 34px rgba(3, 8, 18, 0.22)',
  '--app-panel-gradient': 'linear-gradient(180deg, rgba(17, 27, 42, 0.96), rgba(11, 18, 29, 0.94))',
  '--app-card-gradient': 'linear-gradient(180deg, rgba(14, 23, 36, 0.78), rgba(10, 17, 28, 0.74))',
  '--app-card-subtle-gradient': 'linear-gradient(180deg, rgba(20, 33, 54, 0.72), rgba(12, 20, 32, 0.72))',
  '--app-card-support-gradient': 'linear-gradient(180deg, rgba(11, 18, 30, 0.6), rgba(8, 14, 24, 0.58))',
  '--app-card-caution-gradient': 'linear-gradient(180deg, rgba(22, 20, 26, 0.7), rgba(15, 14, 19, 0.68))',
  '--app-action-gradient': 'linear-gradient(180deg, rgba(28, 48, 80, 0.98), rgba(19, 33, 55, 0.98))',
  '--app-button-gradient': 'linear-gradient(180deg, rgba(31, 54, 90, 0.98), rgba(24, 40, 67, 0.98))',
  '--app-choice-gradient': 'linear-gradient(180deg, rgba(12, 19, 31, 0.52), rgba(9, 15, 24, 0.48))',
  '--app-choice-hover-gradient': 'linear-gradient(180deg, rgba(20, 31, 49, 0.7), rgba(14, 22, 35, 0.68))',
  '--app-choice-selected-gradient': 'linear-gradient(180deg, rgba(28, 45, 74, 0.92), rgba(18, 31, 52, 0.9))',
  '--vf-primary-action-bg': theme.visualHierarchy.primaryAction.background,
  '--vf-primary-action-bg-hover': theme.visualHierarchy.primaryAction.backgroundHover,
  '--vf-primary-action-border': theme.visualHierarchy.primaryAction.border,
  '--vf-primary-action-shadow': theme.visualHierarchy.primaryAction.shadow,
  '--vf-primary-action-text': theme.visualHierarchy.primaryAction.text,
  '--vf-support-bg': theme.visualHierarchy.supportPanel.background,
  '--vf-support-border': theme.visualHierarchy.supportPanel.border,
  '--vf-support-text': theme.visualHierarchy.supportPanel.text,
  '--vf-quiet-bg': theme.visualHierarchy.quietPanel.background,
  '--vf-quiet-border': theme.visualHierarchy.quietPanel.border,
  '--vf-quiet-text': theme.visualHierarchy.quietPanel.text,
  '--vf-disclosure-bg': theme.visualHierarchy.disclosure.background,
  '--vf-disclosure-border': theme.visualHierarchy.disclosure.border,
  '--vf-app-accent-heading': theme.visualHierarchy.appAccent.heading,
  '--vf-app-accent-heading-soft': theme.visualHierarchy.appAccent.headingSoft,
  '--vf-app-accent-icon': theme.visualHierarchy.appAccent.icon,
  '--vf-app-accent-rule': theme.visualHierarchy.appAccent.rule,
  '--vf-app-accent-chip-bg': theme.visualHierarchy.appAccent.chipBackground,
  '--vf-app-accent-chip-border': theme.visualHierarchy.appAccent.chipBorder,
  '--vf-step-index-bg': theme.visualHierarchy.scanStructure.stepIndexBackground,
  '--vf-step-index-border': theme.visualHierarchy.scanStructure.stepIndexBorder,
  '--vf-step-row-bg': theme.visualHierarchy.scanStructure.stepRowBackground,
  '--vf-step-row-border': theme.visualHierarchy.scanStructure.stepRowBorder,
  '--vf-option-row-bg': theme.visualHierarchy.scanStructure.optionRowBackground,
  '--vf-option-row-border': theme.visualHierarchy.scanStructure.optionRowBorder,
  '--vf-bottom-nav-bg': theme.visualHierarchy.bottomNav.background,
  '--vf-bottom-nav-active-bg': theme.visualHierarchy.bottomNav.activeBackground,
  '--vf-bottom-nav-active-border': theme.visualHierarchy.bottomNav.activeBorder,
  '--vf-bottom-nav-shadow': theme.visualHierarchy.bottomNav.shadow,
  '--vf-mobile-app-inline-padding': theme.visualHierarchy.mobileViewport.appInlinePadding,
  '--vf-mobile-app-header-padding': theme.visualHierarchy.mobileViewport.appHeaderPadding,
  '--vf-mobile-app-header-gap': theme.visualHierarchy.mobileViewport.appHeaderGap,
  '--vf-mobile-app-icon-button-size': theme.visualHierarchy.mobileViewport.appIconButtonSize,
  '--vf-mobile-app-panel-padding': theme.visualHierarchy.mobileViewport.appPanelPadding,
  '--vf-mobile-app-panel-radius': theme.visualHierarchy.mobileViewport.appPanelRadius,
  '--vf-mobile-app-narrow-panel-radius': theme.visualHierarchy.mobileViewport.appNarrowPanelRadius,
  '--vf-mobile-bottom-nav-item-basis': theme.visualHierarchy.mobileViewport.bottomNavItemBasis,
  '--vf-marketing-accent-card-bg': theme.visualHierarchy.marketing.accentCardBackground,
  '--vf-marketing-quiet-card-bg': theme.visualHierarchy.marketing.quietCardBackground,
  '--vf-decision-gap': 'clamp(0.85rem, 1.7vw, 1.15rem)',
  '--vf-section-gap': 'clamp(1rem, 2vw, 1.35rem)',
  '--vf-primary-radius': '1.28rem',
  '--vf-secondary-radius': '1.05rem',
  '--vf-tertiary-radius': '0.9rem',
  '--vf-button-min-height': '2.85rem',
  '--vf-shell-content-width': 'min(56rem, 100%)',
  '--fs-body': theme.typography.body.size,
  '--fs-subhead': theme.typography.subhead.size,
  '--fs-page-title': theme.typography.appTitle.size,
  '--fs-marketing-hero': theme.typography.hero.mobileSize,
  '--lh-body': String(theme.typography.body.lineHeight),
  '--lh-loose': String(theme.typography.bodyLoose.lineHeight),
  '--measure-read': theme.typography.measure.readingTarget,
  '--measure-max': theme.typography.measure.readingMax,
  '--hit-min': `${theme.interaction.targetMin}px`,
  '--hit-gap': `${theme.interaction.targetGap}px`,
} as const;
